resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 1a61614cabfd6b91c6afd6d9e172cc5b838c65fe

jobs:
- job: Linux_Build
  timeoutInMinutes: 150
  variables:
    skipComponentGovernanceDetection: true
  workspace:
    clean: all
  pool: Linux-CPU-2019
  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
